name: BFast
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flame: ^0.27.0
  shared_preferences: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/click_screen.png
    - assets/images/click_screen2.png
    - assets/images/home_screen.png
    - assets/images/beehive.png
    - assets/images/wait_screen.png
    - assets/images/wait_screen2.png
    - assets/images/score_toosoon_screen.png
    - assets/images/too_soon_screen.png
    - assets/images/score_screen.png
    - assets/images/get_ready_screen.png
    - assets/images/extra_screen.png
    - assets/images/lost_screen.png
    - assets/images/lost_screen2.png
    - assets/images/callout.png
    - assets/images/wasp1_wing_up.png
    - assets/images/wasp1_wing_down.png
    - assets/images/wasp1_dead.png
    - assets/images/wasp2_wing_up.png
    - assets/images/wasp2_wing_down.png
    - assets/images/wasp2_dead.png
    - assets/images/wasp3_wing_up.png
    - assets/images/wasp3_wing_down.png
    - assets/images/wasp3_dead.png
    - assets/images/wasp4_wing_up.png
    - assets/images/wasp4_wing_down.png
    - assets/images/wasp4_dead.png
    - assets/images/wasp5_wing_up.png
    - assets/images/wasp5_wing_down.png
    - assets/images/wasp5_dead.png
    - assets/images/long-grass.png
    - assets/images/logo_circle.png
    - assets/images/sad_bee.png
    - assets/images/good_job_bee.png
    - assets/images/mode_button.png
    - assets/images/long_button.png
    - assets/images/play_again_long_button.png
    - assets/images/play_again_circle_button.png
    - assets/images/home_circle_button.png
    - assets/images/home_long_button.png
    - assets/images/start_circle_button.png
    - assets/images/start_long_button.png
    - assets/images/mode1_button.png
    - assets/images/mode2_button.png
    - assets/images/mode3_button.png
    - assets/images/mode4_button.png


