name: BFast
description: Interactive reaction time game.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flame: ^0.27.0
  flutter_launcher_icons: ^0.8.1
  shared_preferences: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:  
  android: "launcher_icon"
  image_path: "assets/images/logo3.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/click_screen.png
    - assets/images/click_screen2.png
    - assets/images/home_screen.png
    - assets/images/beehive.png
    - assets/images/wait_screen.png
    - assets/images/wait_screen2.png
    - assets/images/score_toosoon_screen.png
    - assets/images/too_soon_screen.png
    - assets/images/score_screen.png
    - assets/images/get_ready_screen.png
    - assets/images/extra_screen.png
    - assets/images/lost_screen.png
    - assets/images/lost_screen2.png
    - assets/images/callout.png
    - assets/images/wasp1_wing_up.png
    - assets/images/wasp1_wing_down.png
    - assets/images/wasp1_dead.png
    - assets/images/wasp2_wing_up.png
    - assets/images/wasp2_wing_down.png
    - assets/images/wasp2_dead.png
    - assets/images/wasp3_wing_up.png
    - assets/images/wasp3_wing_down.png
    - assets/images/wasp3_dead.png
    - assets/images/wasp4_wing_up.png
    - assets/images/wasp4_wing_down.png
    - assets/images/wasp4_dead.png
    - assets/images/wasp5_wing_up.png
    - assets/images/wasp5_wing_down.png
    - assets/images/wasp5_dead.png
    - assets/images/long-grass.png
    - assets/images/logo_circle.png
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/logo3.png
    - assets/images/sad_bee.png
    - assets/images/good_job_bee.png
    - assets/images/mode_button.png
    - assets/images/long_button.png
    - assets/images/play_again_long_button.png
    - assets/images/play_again_circle_button.png
    - assets/images/home_circle_button.png
    - assets/images/home_long_button.png
    - assets/images/start_circle_button.png
    - assets/images/start_long_button.png
    - assets/images/mode1_button.png
    - assets/images/mode2_button.png
    - assets/images/mode3_button.png
    - assets/images/mode4_button.png
    - assets/images/how_to_play.png
    - assets/images/how_to_play2.png
    - assets/images/credits.png
    - assets/images/bee1.png
    - assets/images/bee2.png
    - assets/images/bee3.png
    - assets/images/bee4.png
    - assets/images/bee5.png
    - assets/images/beehive_3.png
